### ISSUE TITLE
Communication between processes

### ISSUE THREAD

**Issue by kenenbek** [bgmerrell/simgo#3]
Do you know a correct way how communication between `simgo.Process`es via golang channels is done? I tried to create a global variable of type `chan int` and used it for communication like:
```
func (c *Host) send(env *simgo.Environment, pc *simgo.ProcComm) interface{} {
    for{
        fmt.Printf("Start sending at %d\n", env.Now)
        x := 5
        link <- x
        to := simgo.NewTimeout(env, uint64(x / 1), nil)
        to.Schedule(env)
	pc.Yield(to.Event)
	fmt.Printf("End sending at %d\n", env.Now)
    }
}
```
 but I got a `deadlock` problem. Here is the full simple example based on `electric_car.go` https://gist.github.com/kenenbek/c651b921470f088f53fbc1ab60bdb622

**Comment by bgmerrell** [comment]
Hi @kenenbek.

I don't think there is currently a good way to communicate between processes using channels.  The fundamental reason for this is because `simgo`, like `simpy`, is essentially single-threaded, and the reason for that is simplicity.  Simgo does use goroutines, but it's only to implement coroutines; simpy uses generators for this.  Here's why what you're doing won't work currently:

1. `NewSender` is called, so a new `send` process is initialized (and scheduled), waits to be resumed
2. `NewReceiver` is called, so a New `receive` process is initialized (and scheduled), waits to be resumed
3. env.Run() is called, which starts the simgo core to step through all scheduled events
4. simgo core code steps and calls the resume callback for the `send` process
5. `link <- x` is excuted, and blocks forever because there is not another goroutine
       running to read from the `link` channel.  This is why you see the "fatal error: all
       goroutines are asleep" message.



Allowing for parallism in a discrete event simulation environment becomes a lot more complicated.  In the future, to improve performance vs. simpy, I'd like to figure out a way to make simgo run things in parallel, but that won't be happening for a while.

I think we just need to get shared resources implemented to accomplish what you're wanting to do: http://simpy.readthedocs.io/en/latest/examples/process_communication.html
